/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Flash.c
**     Project     : Proj
**     Processor   : S32K144_100
**     Component   : flash
**     Version     : Component 1.0.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2024-10-29, 13:56, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file Flash.c
** @version 01.00
*/         
/*!
**  @addtogroup Flash_module Flash module documentation
**  @{
*/         
/* Module Flash.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variable will be used in other source files in application code.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 11.1, Conversion between a pointer
 * to function and another type.
 * The cast is required to define a callback function.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 11.6, A cast shall not be performed
 * between pointer to void and an arithmetic type.
 * The cast is required to initialize a pointer with an unsigned int define,
 * representing an address.
 */

#include "Flash.h"


/*! @brief Configuration structure flashCfg_0 */
const flash_user_config_t Flash_InitConfig = {
    .PFlashBase  = 0x00000000U,                     /* Base address of Program Flash block */
    .PFlashSize  = 0x00080000U,                     /* Size of Program Flash block         */
    .DFlashBase  = 0x10000000U,                     /* Base address of Data Flash block    */
    .EERAMBase   = 0x14000000U,                     /* Base address of FlexRAM block */
    /* If using callback, any code reachable from this function must not be placed in a Flash block targeted for a program/erase operation.*/
    .CallBack    = NULL_CALLBACK
};

/* Declare a FLASH config struct which initialized by FlashInit, and will be used by all flash operations */
static flash_ssd_config_t flashSSDConfig;


void InitFlash(void)
{
    /* Init flash */
	FLASH_DRV_Init(&Flash_InitConfig, &flashSSDConfig);
}

status_t WriteFlash(uint32_t startAddr, uint32_t size, const uint8_t * pData)
{
    status_t ret;
    ret = FLASH_DRV_Program(&flashSSDConfig, startAddr, size, pData);
    return ret;
}

status_t EraseFlash(uint32_t startAddr, uint32_t size)
{
    status_t ret;
    ret = FLASH_DRV_EraseSector(&flashSSDConfig, startAddr, size);
    return ret;
}


// Flash 测试 --- P-Flash 最小单位是 16，D-Flash 最小单位是 8. 数据写入时注意对齐。擦除最小单位 4096
uint8_t testBuf[512] = {0x01, 0x02, 0x03, 0x04};
volatile unsigned int test_k = 0;
void FlashTest(void)
{
    // 擦除所有 D-Flash 区域 - BaseAddr: 0x10000000; Size: 0x10000
    test_k = FLASH_DRV_EraseSector(&flashSSDConfig, 0x10000000, 0x10000);
    // 往 D-Flash 0x10000000 地址处写入数据
    test_k = FLASH_DRV_Program(&flashSSDConfig, 0x10000000, 32, testBuf);

    // 擦除 P-Flash - BaseAddr: 0x00013000; Size: 4096
    test_k = FLASH_DRV_EraseSector(&flashSSDConfig, 0x00013000, 4096);
    // 往 P-Flash 0x00013000 地址处写入数据
    test_k = FLASH_DRV_Program(&flashSSDConfig, 0x00013000, 32, testBuf);
}

/* END Flash. */

